# This CI job installs Crystal and shard dependencies, then executes `crystal spec` to run the test suite
# More configuration options are available at https://crystal-lang.github.io/install-crystal/configurator.html

on:
  push:
  pull_request:
    branches: [master]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec --order=random
      - name: Build
        run: shards build
      - name: Check formatting
        run: crystal tool format; git diff --exit-code
        if: matrix.os == 'ubuntu-latest'
      - uses: actions/upload-artifact@v2
        with:
          name: binary
          path: bin/*
